# Generated by Django 5.1.4 on 2025-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_submission_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='start_time',
            field=models.IntegerField(blank=True, default=1740329574.10525, null=True),
        ),
    ]
