# Generated by Django 5.1.4 on 2025-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_course_discount_alter_course_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='image',
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='phone',
            field=models.CharField(default=1234, max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='start_time',
            field=models.IntegerField(blank=True, default=1740419375.09357, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late'), ('missing', 'Missing')], default='pending', max_length=50),
        ),
    ]
