# Generated by Django 5.1.3 on 2026-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_assignment_image_alter_billingdetails_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='start_time',
            field=models.IntegerField(blank=True, default=1772036346.521896, null=True),
        ),
    ]
