# Generated by Django 5.1.3 on 2026-02-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_submission_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='start_time',
            field=models.IntegerField(blank=True, default=1772040059.192791, null=True),
        ),
    ]
