# Generated by Django 5.1.3 on 2026-02-25 17:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_submission_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='start_time',
            field=models.IntegerField(blank=True, default=app.models.get_current_timestamp, null=True),
        ),
    ]
