# Generated by Django 5.2.1 on 2026-03-17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def map_activity_type_forward(apps, schema_editor):
    UserActivity = apps.get_model("analytics", "UserActivity")
    mapping = {
        "video_watched": "VIDEO_WATCH",
        "lesson_completed": "VIDEO_WATCH",
        "quiz_completed": "QUIZ_ATTEMPT",
        "assignment_submitted": "ASSIGNMENT_SUBMIT",
        "course_completed": "COURSE_COMPLETE",
        "login": "LOGIN",
    }
    for old_value, new_value in mapping.items():
        UserActivity.objects.filter(activity_type=old_value).update(activity_type=new_value)


def map_activity_type_backward(apps, schema_editor):
    UserActivity = apps.get_model("analytics", "UserActivity")
    mapping = {
        "VIDEO_WATCH": "video_watched",
        "QUIZ_ATTEMPT": "quiz_completed",
        "ASSIGNMENT_SUBMIT": "assignment_submitted",
        "COURSE_COMPLETE": "course_completed",
        "LOGIN": "login",
    }
    for old_value, new_value in mapping.items():
        UserActivity.objects.filter(activity_type=old_value).update(activity_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseanalytics",
            name="course",
            field=models.ForeignKey(
                db_index=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_snapshots",
                to="courses.course",
            ),
        ),
        migrations.RemoveField(
            model_name="courseanalytics",
            name="avg_completion_percent",
        ),
        migrations.RemoveField(
            model_name="courseanalytics",
            name="snapshot_date",
        ),
        migrations.RemoveField(
            model_name="courseanalytics",
            name="total_completions",
        ),
        migrations.RemoveField(
            model_name="courseanalytics",
            name="total_views",
        ),
        migrations.RemoveField(
            model_name="courseanalytics",
            name="total_watch_time_seconds",
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="average_assignment_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="average_progress",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="average_quiz_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="completed_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="rating_average",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="total_lessons",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="total_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RenameField(
            model_name="useractivity",
            old_name="event_type",
            new_name="activity_type",
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="user_activi_course__30efec_idx",
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="user_activi_user_id_0807c4_idx",
        ),
        migrations.RunPython(map_activity_type_forward, map_activity_type_backward),
        migrations.RemoveField(
            model_name="useractivity",
            name="course",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="video",
        ),
        migrations.AddField(
            model_name="useractivity",
            name="reference_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("VIDEO_WATCH", "Video Watch"),
                    ("QUIZ_ATTEMPT", "Quiz Attempt"),
                    ("ASSIGNMENT_SUBMIT", "Assignment Submit"),
                    ("COURSE_COMPLETE", "Course Complete"),
                    ("LOGIN", "Login"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="courseanalytics",
            index=models.Index(
                fields=["course", "last_updated"],
                name="course_analy_course_last_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user", "timestamp"], name="user_activi_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="user_activi_type_time_idx",
            ),
        ),
    ]
