# Generated by Django 5.2.1 on 2026-03-17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("STRIPE", "Stripe"), ("EASYPAISA", "EasyPaisa")],
                        default="STRIPE",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "indexes": [
                    models.Index(fields=["student"], name="orders_stude_8ff1e4_idx"),
                    models.Index(fields=["course"], name="orders_cours_d913ec_idx"),
                    models.Index(fields=["order_status"], name="orders_order_8b56dc_idx"),
                    models.Index(fields=["student", "order_status"], name="orders_stude_336cf7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("student", "course"), name="unique_student_course_order"),
                ],
            },
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[("STRIPE", "Stripe"), ("EASYPAISA", "EasyPaisa")],
                        default="STRIPE",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payment_data", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "indexes": [
                    models.Index(fields=["payment_status"], name="payments_paym_9f1a56_idx"),
                    models.Index(fields=["payment_provider", "payment_status"], name="payments_paym_093805_idx"),
                ],
            },
        ),
        migrations.RenameField(
            model_name="billingdetails",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="billingdetails",
            old_name="postcode",
            new_name="postal_code",
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddIndex(
            model_name="billingdetails",
            index=models.Index(fields=["user", "created_at"], name="billing_det_user_id_987320_idx"),
        ),
    ]
