# Generated by Django 5.2.1 on 2026-03-10 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubePlaylistImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('videos_imported', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_imports', to='courses.course')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_imports', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_imports', to='lessons.lesson')),
            ],
            options={
                'db_table': 'youtube_playlist_imports',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('cloudinary', 'Cloudinary'), ('aws_s3', 'AWS S3')], db_index=True, default='youtube', max_length=20)),
                ('youtube_id', models.CharField(blank=True, default='', max_length=50)),
                ('cloudinary_public_id', models.CharField(blank=True, default='', max_length=300)),
                ('cloudinary_url', models.URLField(blank=True, default='', max_length=500)),
                ('s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('s3_bucket', models.CharField(blank=True, default='', max_length=200)),
                ('s3_url', models.URLField(blank=True, default='', max_length=500)),
                ('thumbnail', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lesson')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='videos_lesson__ccba4b_idx'), models.Index(fields=['course', 'source_type'], name='videos_course__3a2c90_idx')],
            },
        ),
    ]
