# Generated by Django 5.1.3 on 2026-03-12 06:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_course_fields_and_new_models'),
        ('enrollments', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watch_time_seconds', models.PositiveIntegerField(default=0)),
                ('last_position_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'video_progress',
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress_percent',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_status'], name='enrollments_enrollm_c33d9d_idx'),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('student', 'video')},
        ),
    ]
