# Generated by Django 5.2.1 on 2026-03-10 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_watch_time_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('avg_completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('snapshot_date', models.DateField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.course')),
            ],
            options={
                'db_table': 'course_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('video_watched', 'Video Watched'), ('lesson_completed', 'Lesson Completed'), ('quiz_completed', 'Quiz Completed'), ('assignment_submitted', 'Assignment Submitted'), ('course_completed', 'Course Completed'), ('login', 'Login')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video')),
            ],
            options={
                'db_table': 'user_activities',
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='user_activi_user_id_0807c4_idx'), models.Index(fields=['course', 'event_type'], name='user_activi_course__30efec_idx')],
            },
        ),
    ]
