# Generated by Django 5.1.3 on 2026-03-12 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_course_fields_and_new_models'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_text', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'review_responses',
            },
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('rejected', 'Rejected')], db_index=True, default='published', max_length=20),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['student'], name='reviews_student_63e8fa_idx'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_response', to='reviews.review'),
        ),
    ]
